### ISSUE TITLE
multiple NotSpam

### ISSUE THREAD

**Issue by aniserg** [johndoh/roundcube-markasjunk2#58]
Hi! We use roundcube 1.3.6 and markasjunk2 1.12
Selecting multiple messages and marking them as notspam doesn't work. Headers become edited, but messages remain in SPAM folder.. Is it bug?

**Comment by Philippe23** [comment]
I'm seeing the same on roundcube 1.3.6 and markasjunk2 1.11.2.

**Comment by johndoh** [comment]
1.12, which has not been released yet, will not work with rc 1.3.x. It requires current rc git-master.

I think I might have figured out the issue though so please try with latest 1.11 branch and also please tell me which driver you are using.

**Comment by aniserg** [comment]
I've tried 1.11.2 and edit_headers driver - same result.

**Comment by johndoh** [comment]
I think b114734 (23d99bc for release-1.11) fixed the issuse. Try with latest 1.11 branch. If not please reopen with more detail.

**Comment by Philippe23** [comment]
I just tried with 23d99bc (1.11) and the issue persists.

I'm using the `cmd_learn` driver.

Happens with trying to mark a single message as "not junk" for me.

Message disappears from the message list after clicking the "not junk" button, but if I go to another folder and return, the message is actually still there.

What can I do to provide more information about what might be failing?

(Sorry, I'm unable to reopen the issue since I'm not the original submitter.)

**Comment by johndoh** [comment]
you may have a different issue. what is the ham command you are running?

does the "Message(s) moved successfully." appear in the UI?

**Comment by Philippe23** [comment]
Yes, both "Messages moved successfully" and "Message marked as ham" appear.

I just realized dragging and dropping and using the move-to menu fail, so the bug I'm seeing is in Roundcube proper, not markasjunk2.

Sorry for the trouble/confusion.

**Comment by Philippe23** [comment]
Oh, and thanks for troubleshooting with me, and thanks for making this plugin!
